version: "3.8"
services: 
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    container_name: node-api
    command: npm run dev
    environment:
      BCRYPT_SALT: 30
      PORT: 3333
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
    restart: always