version: "3.8"
services: 
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:latest
    container_name: node-api
    command: npm run dev
    env_file:
      - .env
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app/
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste-banco
    ports:
      - 5432:5432
    restart: always
    